language: cpp
compiler: gcc
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: linux
script:
 - cd Platform.Data.Triplets.Kernel
 - export LIBRARY_PATH=$(pwd)
 - make
 - sudo cp Platform.Data.Triplets.Kernel.so /usr/lib
 - ./test
