language: cpp
compiler: gcc
sudo: required
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: linux
    - os: windows
      script:
       - cd Platform.Data.Triplets.Kernel
       - mingw32-make
       - dir
       - dir /c/Users/travis/.travis/functions
       - hello
       - test
script:
 - cd Platform.Data.Triplets.Kernel
 - make
 - export LD_LIBRARY_PATH=$(pwd)
 - ./test
