language: cpp
compiler: gcc
matrix:
  include:
    - os: osx
      script:
       - cd Platform.Data.Triplets.Kernel
       - make
       - ./test
    - os: linux
      before_install:
       - export TARGET_PLATFORM="linux-x64"
       - export TRAVIS_REPO_NAME=$(echo "${TRAVIS_REPO_SLUG#*/}" | sed 's/.*/\u&/')
       - export SOURCE_BRANCH="master"
      script:
       - cd Platform.Data.Triplets.Kernel
       - make
       - export LD_LIBRARY_PATH=$(pwd)
       - ./test
       - cd ..
      after_success:
       - bash ./publish-binaries.sh
    - os: windows
      script:
       - cd Platform.Data.Triplets.Kernel
       - mingw32-make
       - ./test

