language: cpp
compiler: gcc
matrix:
  include:
    - os: osx
      script:
       - cd Platform.Data.Triplets.Kernel
       - make
       - ./test
    - os: linux
      script:
       - cd Platform.Data.Triplets.Kernel
       - make
       - export LD_LIBRARY_PATH=$(pwd)
       - ./test
    - os: windows
      script:
       - cd Platform.Data.Triplets.Kernel
       - mingw32-make
       - ./test

